### ISSUE TITLE
Efficiently adding records to the Distributions table

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#590]
When an admin needs to add a species to the distribution table, they have to add records for each state and county individually. It would make life easier if and admin had the ability to add a new species to

1. all New England states
2. all New England counties
3. North American states (US and Canada)

**Comment by sidkoul** [comment]
Looking at the distribution record locations:
```
A.         6 NE states
B.        67 NE counties
C.        44 States outside NE
D.     +  13 Canadian provinces and territories
------------------------------- 
E.       130 Total Records
```
We have implemented a button that adds locations from row E. This is useful for adding *new* records.

But because the admins are also filling in partial or missing records, it's also useful to have buttons that add locations from 

- Row B (New England counties)
- Rob C and D (States outside NE and Canadian provinces and territories)

**Comment by jnga** [comment]
If you press the Add a Set of Distribution Records button, the notes on the next screen mention, "Any existing records for this plant will be left alone."

The intent here is to allow filling in partial or missing records. After that, one would just search on the plant name in order to get the list of 130 records, check or uncheck any values in the list as needed, and press Save.

Now that I look at the "any existing records" note again, I think it could be clarified, so I will do that.

Please give this workflow a try and see if you think it is adequate in practice.
