### ISSUE TITLE
Map problem with Ranunculus aquatilis data

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#638]
Arthur reports:
For Ranunculus aquatilis, note that Carrol County, NH (eastern part of state) is not displaying as a county where this plant occurs (it is light green, should be dark green).  It is checked in the database.  So why wouldn't it be displaying properly?  Any thoughts.

https://gobotany.newenglandwild.org/species/ranunculus/aquatilis/

**Comment by jnga** [comment]
The record is fixed in Production and Dev for Ranuculus aquatilis, so the map is correctly shaded there now.

The problem was that Carroll County was misspelled 'Caroll' in the database when the bulk-create function was used. This is corrected in the code now, but there are still a few more data items with this, affecting three other maps.
