### ISSUE TITLE
Dkey fig link 755 for Oxalis

### ISSUE THREAD

**Issue by sidkoul** [newfs/gobotany-app#654]
On this page: https://gobotany.newenglandwild.org/dkey/oxalis/#c5 one of the references to “Fig. 755" isn't linked to the corresponding illustration.

**Comment by jnga** [comment]
Fixed this locally and in Dev via the Admin. Because this requires a change to the Admin made in Release 2.6, the fix will have to be applied in Production after 2.6 is released.

Steps:

In the Admin, under DKey, choose Leads.

Search on 755.

Pick the 5a record. Look in the text for "R image]"--change this to just be "R]" (like the other links).

Reload the page and verify the fix: the image tooltip on that link should now work.

Run the DKey sync script as directed in the ReadMe.
